apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: configmap-updater-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "create", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: configmap-updater-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: configmap-updater-role
subjects:
  - kind: ServiceAccount
    name: itgenius-serviceaccount
    namespace: default
